name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy .env.example to .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Increase memory limit
      run: echo "memory_limit=-1" >> $GITHUB_PATH

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install Passport
      run: |
        composer require laravel/passport

    - name: Run Migrations
      run: php artisan migrate --seed

    - name: Install Passport Keys
      run: php artisan passport:install

    - name: Run Tests
      run: vendor/bin/phpunit
