name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy .env.example to .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Setup Environment Variables
      run: |
        export DB_CONNECTION=mysql
        export DB_HOST=127.0.0.1
        export DB_PORT=3306
        export DB_DATABASE=$(grep DB_DATABASE .env | cut -d '=' -f2)
        export DB_USERNAME=$(grep DB_USERNAME .env | cut -d '=' -f2)
        export DB_PASSWORD=$(grep DB_PASSWORD .env | cut -d '=' -f2)

    - name: Start MySQL Service
      run: docker run --name test -e MYSQL_ROOT_PASSWORD=${DB_PASSWORD} -d mysql:8.0
      env:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_RANDOM_ROOT_PASSWORD: '1'

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Increase memory limit
      run: echo "memory_limit=-1" >> $GITHUB_PATH

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Install Passport, CORS, and ForceJsonResponse
      run: |
        composer require laravel/passport

    - name: Run Migrations
      run: php artisan migrate --seed

    - name: Install Passport Keys
      run: php artisan passport:install

    - name: Run Tests
      run: vendor/bin/phpunit
      
    - name: Debug Database Connection
      run: php artisan tinker --eval "print_r(config('database.connections.mysql'));"
